name: "BoM Radar Proxy"
version: "2.0.2"
slug: bom_radar_proxy
description: "Bureau of Meteorology radar image proxy with intelligent caching"
url: "https://github.com/safepay/addon-bom-radar-proxy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  3000/tcp: null
ports_description:
  3000/tcp: "Internal API port (not exposed)"
ingress: true
ingress_port: 3000
panel_icon: mdi:radar
panel_title: "BoM Radar Proxy"
hassio_api: true
options:
  log_level: "info"
  cache_ttl_hours: 24
  timestamp_refresh_interval: 600
  max_cache_size_mb: 1000
schema:
  log_level: list(debug|info|warn|error)
  cache_ttl_hours: int(1,168)
  timestamp_refresh_interval: int(300,3600)
  max_cache_size_mb: int(100,10000)
