name: "BoM Radar Proxy"
version: "2.0.12"
slug: bom_radar_proxy
description: "Bureau of Meteorology radar image proxy with intelligent caching"
url: "https://github.com/safepay/addon-bom-radar-proxy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_port: 3000
ingress_entry: "/"
webui: "http://[HOST]:[PORT:3000]"
panel_icon: mdi:radar
panel_title: "BoM Radar Proxy"
hassio_api: true
hassio_role: default
auth_api: false
homeassistant_api: false
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "API port for cards and integrations"
options:
  log_level: "info"
  cache_ttl_hours: 24
  timestamp_refresh_interval: 600
  max_cache_size_mb: 1000
schema:
  log_level: list(debug|info|warn|error)
  cache_ttl_hours: int(1,168)
  timestamp_refresh_interval: int(300,3600)
  max_cache_size_mb: int(100,10000)
