build_from:
  aarch64: "ghcr.io/hassio-addons/base-aarch64:15.0.1"
  amd64: "ghcr.io/hassio-addons/base-amd64:15.0.1"
  armhf: "ghcr.io/hassio-addons/base-armhf:15.0.1"
  armv7: "ghcr.io/hassio-addons/base-armv7:15.0.1"
  i386: "ghcr.io/hassio-addons/base-i386:15.0.1"
labels:
  org.opencontainers.image.title: "BoM Radar Proxy"
  org.opencontainers.image.description: "Bureau of Meteorology radar image proxy with caching"
  org.opencontainers.image.source: "https://github.com/safepay/leaflet-bom-radar"
  org.opencontainers.image.licenses: "MIT"
