name: "BoM Radar Proxy"
version: "2.0.0"
slug: bom_radar_proxy
description: "Bureau of Meteorology radar image proxy with intelligent caching"
url: "https://github.com/safepay/leaflet-bom-radar"
documentation: "https://github.com/safepay/leaflet-bom-radar/blob/main/bom-radar-proxy/DOCS.md"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
ports:
  3000/tcp: null
ports_description:
  3000/tcp: "Internal API port (not exposed)"
ingress: true
ingress_port: 3000
ingress_stream: false
panel_icon: mdi:radar
panel_title: "BoM Radar Proxy"
hassio_api: true
hassio_role: default
options:
  log_level: "info"
  cache_ttl_hours: 24
  timestamp_refresh_interval: 600
  max_cache_size_mb: 1000
schema:
  log_level: list(debug|info|warn|error)
  cache_ttl_hours: int(1,168)
  timestamp_refresh_interval: int(300,3600)
  max_cache_size_mb: int(100,10000)
image: "ghcr.io/{arch}-addon-bom-radar-proxy"
